# Generated by Django 4.2.13 on 2026-05-31 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('grade_level', models.CharField(max_length=20)),
                ('section', models.CharField(blank=True, max_length=10)),
                ('academic_year', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
                'ordering': ['academic_year', 'grade_level', 'section', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('assigned_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='teacher.class')),
            ],
            options={
                'verbose_name': 'homework',
                'verbose_name_plural': 'homework',
                'ordering': ['-assigned_date', 'due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('parent_contact', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject_specialization', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
                'ordering': ['user__fullname'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=80)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('slot_type', models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Lab'), ('sports', 'Sports'), ('free', 'Free')], default='lecture', max_length=10)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='teacher.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'timetable slot',
                'verbose_name_plural': 'timetable slots',
                'ordering': ['day_of_week', 'start_time', 'klass__name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherClassAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=80)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='teacher.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'teacher class assignment',
                'verbose_name_plural': 'teacher class assignments',
                'ordering': ['klass__academic_year', 'klass__grade_level', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_notes', models.TextField(blank=True)),
                ('submission_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('late', 'Late')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='teacher.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='teacher.student')),
            ],
            options={
                'verbose_name': 'homework submission',
                'verbose_name_plural': 'homework submissions',
                'ordering': ['homework__due_date', 'student__full_name'],
            },
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='teacher.teacher'),
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('active', 'Active'), ('transferred', 'Transferred'), ('dropped', 'Dropped')], default='active', max_length=12)),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_created', to='teacher.teacher')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='teacher.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='teacher.student')),
            ],
            options={
                'verbose_name': 'class enrollment',
                'verbose_name_plural': 'class enrollments',
                'ordering': ['-enrollment_date', 'student__full_name'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to='teacher.teacher'),
        ),
        migrations.AddConstraint(
            model_name='timetableslot',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='timetable_end_time_after_start_time'),
        ),
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together={('teacher', 'day_of_week', 'start_time'), ('klass', 'day_of_week', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherclassassignment',
            unique_together={('teacher', 'klass', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='homeworksubmission',
            unique_together={('homework', 'student')},
        ),
        migrations.AddConstraint(
            model_name='homework',
            constraint=models.CheckConstraint(check=models.Q(('due_date__gte', models.F('assigned_date'))), name='homework_due_date_on_or_after_assigned_date'),
        ),
        migrations.AddConstraint(
            model_name='classenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student',), name='one_active_class_per_student'),
        ),
    ]
