# Generated by Django 4.2.13 on 2026-06-22 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={},
        ),
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='Primary class teacher who owns this class.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_classes', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='secondary_class_teacher',
            field=models.ForeignKey(blank=True, help_text='Secondary/co-class teacher.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_class_teacher_classes', to='teacher.teacher'),
        ),
    ]
