# Generated by Django 4.2.13 on 2026-06-22 16:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_student_password'),
        ('teacher', '0002_alter_class_options_class_class_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('assigned_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hw_homework', to='teacher.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hw_assigned', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'homework',
                'verbose_name_plural': 'homework',
                'ordering': ['-assigned_date', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_notes', models.TextField(blank=True)),
                ('submission_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('late', 'Late')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hw_submissions', to='homework.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hw_submissions', to='student.student')),
            ],
            options={
                'verbose_name': 'homework submission',
                'verbose_name_plural': 'homework submissions',
                'ordering': ['homework__due_date', 'student__first_name'],
                'unique_together': {('homework', 'student')},
            },
        ),
        migrations.AddConstraint(
            model_name='homework',
            constraint=models.CheckConstraint(check=models.Q(('due_date__gte', models.F('assigned_date'))), name='hw_due_date_on_or_after_assigned_date'),
        ),
    ]
